apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: node-pod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-app
        image: warolv/node-app-x:latest
        imagePullPolicy: IfNotPresent # if exists, will not pull new image
        ports: 
        - containerPort: 80
        - containerPort: 443
